### ISSUE TITLE
Subscribing to tf topics using the rospy.AnyMsg type prevents transform lookups

### ISSUE THREAD

**Issue by barryridge** [ros/geometry2#288]
Minimal example using the turtlebot tutorial:
```python
#!/usr/bin/env python
import rospy
import tf2_ros

def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard something...AnyThing?")
    
def topic_subscriber():
    rospy.Subscriber("/tf", rospy.AnyMsg, callback)

def transform_listener():
    tf2_buffer = tf2_ros.Buffer()
    tf2_listener = tf2_ros.TransformListener(tf2_buffer)
          
    while not (tf2_buffer.can_transform('turtle1', 'world', rospy.Time.now())):
        pass
    
    transform = tf2_buffer.lookup_transform('turtle1', 'world', rospy.Time.now())

    print('I will not get this transform: {}'.format(transform))

if __name__ == '__main__':
    rospy.init_node('tf2_test', anonymous=True)
    topic_subscriber()
    transform_listener()
    rospy.spin()
```

This results in:
```bash
[INFO] [1521201113.590437, 0.000000]: /tf2_test_18929_1521201110605I heard something...AnyThing?
[INFO] [1521201113.590978, 0.000000]: /tf2_test_18929_1521201110605I heard something...AnyThing?
[ERROR] [1521201113.591844, 0.000000]: bad callback: <bound method TransformListener.callback of <tf2_ros.transform_listener.TransformListener instance at 0x7f721a1341b8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/transform_listener.py", line 68, in callback
    for transform in data.transforms:
AttributeError: 'AnyMsg' object has no attribute 'transforms'

[ERROR] [1521201113.592305, 0.000000]: bad callback: <bound method TransformListener.callback of <tf2_ros.transform_listener.TransformListener instance at 0x7f721a1341b8>>
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/transform_listener.py", line 68, in callback
    for transform in data.transforms:
AttributeError: 'AnyMsg' object has no attribute 'transforms'
```

**Comment by tfoote** [comment]
Thanks for the report. It's a little lower level than tf2. I've reticketed it for rospy here: https://github.com/ros/ros_comm/issues/1351
