### ISSUE TITLE
Support for ROS2 Dashing along with python3

### ISSUE THREAD

**Issue by shikharvaish28** [ros/geometry2#397]
```Traceback (most recent call last):
  File "ros_pp.py", line 12, in <module>
    from tf2_ros.src.tf2_ros.transform_listener import TransformListener
  File "../../../src/geometry2/tf2_ros/src/tf2_ros/__init__.py", line 39, in <module>
    from buffer_interface import *
ModuleNotFoundError: No module named 'buffer_interface'
```
I have built the geometry library for my project using `colcon` for ROS2 Dashing and Python 3 and sourced it using `source install/setup.bash` but am getting this error on importing the `TransformListener` from `tf2_ros`. 

My directory structure is as follows:

```
-workspace
         - build
         - install
         - src
                -  my_module
                          - src
                              - file.py
                -  geometry2

```

It would be great if anyone could help me know where exactly the error is coming from.

**Comment by shikharvaish28** [comment]
I'm sorry. I mistakenly opened this issue in ROS repo and not in ROS2. The new link is https://github.com/ros2/geometry2/issues/128
