### ISSUE TITLE
Not able to import some files required to run RAZOR IMU 9dof on ROS

### ISSUE THREAD

**Issue by Govindkm** [ros/geometry2#399]
It shows up like this

started roslaunch server http://govindpc-inspiron-3458:35267/

SUMMARY
========

PARAMETERS
 * /imu_node/accel_x_max: 250.0
 * /imu_node/accel_x_min: -250.0
 * /imu_node/accel_y_max: 250.0
 * /imu_node/accel_y_min: -250.0
 * /imu_node/accel_z_max: 250.0
 * /imu_node/accel_z_min: -250.0
 * /imu_node/calibration_magn_use_extended: True
 * /imu_node/gyro_average_offset_x: 0.0
 * /imu_node/gyro_average_offset_y: 0.0
 * /imu_node/gyro_average_offset_z: 0.0
 * /imu_node/imu_yaw_calibration: 0.0
 * /imu_node/magn_ellipsoid_center: [716.958, 574.914...
 * /imu_node/magn_ellipsoid_transform: [[0.96552, 0.0621...
 * /imu_node/magn_x_max: 600.0
 * /imu_node/magn_x_min: -600.0
 * /imu_node/magn_y_max: 600.0
 * /imu_node/magn_y_min: -600.0
 * /imu_node/magn_z_max: 600.0
 * /imu_node/magn_z_min: -600.0
 * /imu_node/port: /dev/ttyACM0
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    display_3D_visualization_node (razor_imu_9dof/display_3D_visualization.py)
    imu_node (razor_imu_9dof/imu_node.py)

auto-starting new master
process[master]: started with pid [9417]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 030a8dd4-b351-11e9-8cd9-2c6e85216141
process[rosout-1]: started with pid [9430]
started core service [/rosout]
process[imu_node-2]: started with pid [9447]
process[display_3D_visualization_node-3]: started with pid [9448]
Traceback (most recent call last):
  File "/home/govindpc/catkin_ws/src/razor_imu_9dof-indigo-devel/nodes/imu_node.py", line 38, in <module>
    from tf.transformations import quaternion_from_euler
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
ImportError: cannot import name TransformException
/usr/lib/python2.7/dist-packages/visual/materials.py:70: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self.__setattr__(key, value)
Traceback (most recent call last):
  File "/home/govindpc/catkin_ws/src/razor_imu_9dof-indigo-devel/nodes/display_3D_visualization.py", line 36, in <module>
    from tf.transformations import euler_from_quaternion
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
ImportError: cannot import name TransformException
[imu_node-2] process has died [pid 9447, exit code 1, cmd /home/govindpc/catkin_ws/src/razor_imu_9dof-indigo-devel/nodes/imu_node.py __name:=imu_node __log:=/home/govindpc/.ros/log/030a8dd4-b351-11e9-8cd9-2c6e85216141/imu_node-2.log].
log file: /home/govindpc/.ros/log/030a8dd4-b351-11e9-8cd9-2c6e85216141/imu_node-2*.log
[display_3D_visualization_node-3] process has died [pid 9448, exit code 1, cmd /home/govindpc/catkin_ws/src/razor_imu_9dof-indigo-devel/nodes/display_3D_visualization.py __name:=display_3D_visualization_node __log:=/home/govindpc/.ros/log/030a8dd4-b351-11e9-8cd9-2c6e85216141/display_3D_visualization_node-3.log].
log file: /home/govindpc/.ros/log/030a8dd4-b351-11e9-8cd9-2c6e85216141/display_3D_visualization_node-3*.log

**Comment by tfoote** [comment]
What packages do you have installed? and what packages are in your workspace?

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
